version: 2.1
workflows:
  images:
    jobs:
      - fuel
jobs:
  fuel:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker build ./fuel
      - run: docker tag $(docker build ./fuel -q) rollupsync/fuel:latest
      - run: docker login --username jchancehud --password $DOCKER_TOKEN
      - run: docker push rollupsync/fuel:latest
